subreddits <- list(
  'europe (main)' = sort(readLines("subreddits/europe_main")),
  'europe (other)' = sort(readLines("subreddits/europe_other")),
  'europe (scandinavia)' = sort(readLines("subreddits/europe_scandinavia")),
  'north_america' = sort(readLines("subreddits/north_america")),
  'world places' = sort(readLines("subreddits/world_places")),
  'bsd / linux' = sort(readLines("subreddits/bsd_linux")),
  'technology / software' = sort(readLines("subreddits/technology_software")),
  'programming' = sort(readLines("subreddits/programming")),
  'mobile' = sort(readLines("subreddits/mobile")),
  'gaming' = sort(readLines("subreddits/gaming")),
  'general (fun/memes)' = sort(readLines("subreddits/general_fun")),
  'general (serious)' = sort(readLines("subreddits/general_serious")),
  'music' = sort(readLines("subreddits/music")),
  'movies / tv series / comics' = sort(readLines("subreddits/movies_tvseries")),
  'sports' = sort(readLines("subreddits/sports")),
  'french subreddits' = sort(readLines("subreddits/french_subreddits")),
  'politics' = sort(readLines("subreddits/politics")),
  'animal' = sort(readLines("subreddits/animals")),
  'cars' = sort(readLines("subreddits/cars")),
  'finance' = sort(readline("subreddits/finance")),
  'crypto' = sort(readLines("subreddits/crypto")),
  'guns' = sort(readLines("subreddits/guns")),
  'other' = sort(readLines("subreddits/other"))
)
